pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604
  demands: Maven

steps:
- task: Gradle@2
  displayName: 'gradlew build publish'
  inputs:
    gradleWrapperFile: '$(Parameters.wrapperScript)'
    tasks: 'build publish'
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()